# Generated by Django 5.1 on 2025-05-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('template_choisi', models.CharField(default='default', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='produits/')),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendeur.boutique')),
            ],
        ),
    ]
