# Generated by Django 5.1 on 2025-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
